### ISSUE TITLE
[IGNORED ISSUE]

### ISSUE THREAD

**Issue by fhuang566** [cse442-at-ub/project_s23-one-belt-one-road#13] opened 2023-02-25 00:45 UTC
**Task tests**

*Test 1*
1) Open the database tables categories
2) Verify that there is a table named "ShoppingCart"
3) Make certain that the table contains these columns: ProductID, Product Name, Unit Price, Amount, and UserID

**Comment by fhuang566** [comment] 2023-02-25 00:49
**Task tests**

*Test 1*
1) Open the database tables categories
2) Verify that there is a table named "ShoppingCart"
3) Make certain that the table contains product information, such as Name, Unit Price, Amount, and UserID, etc.

**Comment by fhuang566** [comment] 2023-02-26 04:19
We have not set up the database yet, so we will carry this task into next sprint.

**Comment by anht-11** [comment] 2023-03-19 00:05
duplicate of #29, so I will close this issue

**Closed as completed by anht-11** 2023-03-19 00:05 UTC
Labels: IO Task, Processing Task
