### ISSUE TITLE
[IGNORED ISSUE]

### ISSUE THREAD

**Issue by fhuang566** [cse442-at-ub/project_s23-one-belt-one-road#11] opened 2023-02-25 00:26 UTC
**Task tests**

*Test 1*
1) Open the drop down menu bar of the website after login in
2) Verify that there is a "Shopping Cart" option to direct to shopping cart page
3) In the HTML file, make certain that there is a page title named "Shopping Cart"

**Comment by fhuang566** [comment] 2023-02-25 00:35
**Task tests**

*Test 1*
1) Open the drop down menu bar of the website after login in
2) Verify that there is a "Shopping Cart" option to direct to shopping cart page
3) In the HTML file, make certain that there is a page title named "Shopping Cart"

**Comment by anht-11** [comment] 2023-02-25 19:25
Provide the link to the figma wireframe of the shopping cart as well.
EDIT: be detailed in how the shopping cart look like.

**Comment by fhuang566** [comment] 2023-02-26 04:21
This is the task for front end coding and I have attached figma link to one of the tasks which mentions figma.

**Comment by fhuang566** [comment] 2023-02-26 04:21
We have not started coding for front end yet, so we will carry this task into next sprint.

**Comment by fhuang566** [comment] 2023-02-26 04:22
> Provide the link to the figma wireframe of the shopping cart as well. EDIT: be detailed in how the shopping cart look like.

This is the task for front end coding and I have attached figma link to one of the tasks which mentions figma.

**Comment by anht-11** [comment] 2023-03-18 19:53
duplicate of #43, so I will close this issue

**Closed as completed by anht-11** 2023-03-18 19:53 UTC
Labels: UI Task
